CREATE TABLE stories (
  id INTEGER PRIMARY KEY,
  country TEXT NOT NULL,
  ident VARCHAR(4) NOT NULL,
  story TEXT NOT NULL
);

INSERT INTO stories VALUES
(1,'Suomi','EFHK','Olet saapunut Suomeen! Lentokentällä vastaasi tulee hätääntyneen oloinen henkilö. Hän on unohtanut matkalaukkunsa koodin viimeisen numeron. Arvaamalla oikean luvun 1-9 välillä, saat palkinnoksi Heva-haalarimerkin.'),
(2,'Ruotsi','ESSA','Välkommen till Sverige! Etsiessäsi kuumeisesti seuraavan lennon porttia, näet lentokentän lattialla komeilemassa haalarimerkin. Kiiruahtaessasi sitä kohden, huomaat, että sinulla on kilpailija. Molempien tarttuessa haalarimerkkiin päätätte ratkaista taiston kivi-sakset-paperi pelillä. Voittaja saa haalarimerkin.'),
(3,'Tanska','EKCH','Odottaessasi seuraavaa lentoa vieressä istuva lapsi pyytää sinulta apua kotitehtävien ratkaisemiseen. Hän tarjoaa palkinnoksi haalarimerkkiä, mikäli saat kaikki vastaukset oikein.'),
(4,'Viro','EETN','Odotellessasi seuraavaa siirtymää, päätät käydä lentokentän kasinolla. Kasinolla on Blackjack peli, jossa palkintona on haalarimerkki.'),
(5,'Alankomaat','EHAM','Amsterdam tunnetaan kanaaleistaan, ja haluat ostaa lentokentän matkamuistomyymälästä siihen liittyvän pienoismallin. Ostoksen yhteydessä osallistut myymälän wordle-peliin, josta voit voittaa kaupan päälle haalarimerkin.'),
(6,'Andorra','LESU','Nauttiessasi Andorran vuoristoilmasta, huomaat lentokentän pääsisäänkäynnin yhteydessä kojun. Kojussa järjestetään Hirsipuu-peli, jonka voittaja saa haalarimerkin. Päätät tarttua tilaisuuteen ja osallistut peliin.'),
(7,'Turkki','LTAC','Vessakäyntisi jälkeen suuntaat hakemaan laukkusi lokerikosta. Lokerikon vieressä seisoo hermostuneen näköinen henkilö. Hän on unohtanut mihin yhdeksästä lokerosta hän on laittanut matkatavaransa. Jos onnistut arvaamaan oikean lokeron, saat palkinnoksi haalarimerkin.'),
(8,'Kreikka','LGAV','Päätät ostaa matkamuistoksi kreikkalaisen viinapullon lentokentältä. Tarttuessasi pulloon, huomaat ettet ole ainoa pullosta kiinnostunut. Päätätte ratkaista kiistan kivi-sakset-paperi menetelmällä. Voittaja saisi pullon, jonka ohessa on haalarimerkki.'),
(9,'Azerbaidžan','UBBB','Bakun lentokentän odotusaulassa koululainen levittää vihkonsa viereiselle penkille. Hän kysyy, osaisitko auttaa muutamassa matikkatehtävässä. Jos ratkaiset ne oikein, hän lupaa antaa haalarimerkin.'),
(10,'Serbia','LYBE','Belgradin porttialueella opiskelijakerho on pystyttänyt pienen korttipöydän viihdyttääkseen myöhästyneitä matkustajia. Päätät osallistua toiveissa voittaa luvattu haalarimerkki.'),
(11,'Saksa','EDDB','Berliinin lentoaseman kirjakaupan seinällä vilkkuu päivän sana. Myyjä kertoo, että jos ratkaiset sen ennen kuin koneesi lähtee, saat haalarimerkin.'),
(12,'Slovakia','LZIB','Bratislavan turvatarkastuksen jälkeen on pieni opiskelijakoju, jossa voi pelata Hirsipuuta. Jos arvaat sanan oikein ennen kuulutusta saat haalarimerkin.'),
(13,'Sveitsi','LSZB','Bernin lentokentän säilytyslokeroiden luona työntekijä kuiskaa: “Yhteen niistä olen piilottanut haalarimerkin.” Jos arvaat oikean lokeron, haalarimerkki on sinun.'),
(14,'Belgia','EBBR','Brysselin portilla on pieni suklaapuoti, jossa on myynnissä limited edition suklaarasia. Sinä ja toinen asiakas haluatte tämän kyseisen tuotteen sen herkullisen suklaan ja haalarimerkin vuoksi. Myyjä ehdottaa kivi-sakset-paperi -ratkaisua, jolloin kiista saadaan ratkaistua reilusti.'),
(15,'Unkari','LHBP','Budapestin terminaalin kahvilassa opiskelijajärjestö myy kahvia ja järjestää matikkavisan matkustajille. Jos lasket kaikki oikein, saat haalarimerkin.'),
(16,'Romania','LROP','Lentoyhtiön työntekijä odottaa koneen lähtöaikaa ja ehdottaa sinulle pientä peliä. “Minulla on kortit ja haalarimerkki. Katsotaan, kumpi saa 21 ensin.” Matkustajat alkavat seurata vierestä tätä mielenkiintoista spektaakkelia.'),
(17,'Moldova','LUKK','Matkamuistomyymälässä päivän ostokseen sisältyy Wordle-peli. Arvaa oikein ennen kuin kuittitulostin lakkaa surisemasta, niin saat haalarimerkin kaupan päälle.'),
(18,'Irlanti','EIDW','Dublinin lentoaseman kahvilan ilmoitustaululla on Hirsipuu-peli liitutaululle kirjoitettuna. Barista lupaa haalarimerkin jokaiselle asiakkaalle, joka onnistuu voittamaan.'),
(19,'Armenia','UDYZ','Jerevanin lähtöporttien ilmoitustaululla lukee “Mikä portti avautuu ensimmäisenä?”. Jos arvaat oikean numeron, saat palkinnoksi haalarimerkin.'),
(20,'Ukraina','UKBB','Kiovan lentokentän kahvilan vitriinissä on enää yksi erikoiskahvi jäljellä. Sinä ja toinen asiakas ojennatte kätenne yhtä aikaa sitä kohden. Myyjä hymyilee ja ehdottaa kivi-sakset-paperi -ratkaisua. Voittaja saa sekä kahvin, että haalarimerkin.'),
(21,'Portugali','LPPT','Lissabonin terminaalissa on “päivän haaste” -koju, jossa matkustajia pyydetään ratkaisemaan nopeita laskuja. Jos onnistut ratkaisemaan kaikki oikein, opiskelijat palkitsevat sinut haalarimerkillä.'),
(22,'Slovenia','LJLJ','Kuulutus kertoo tunnin viivästyksestä. Lentokenttä järjestää spontaanisti “viihdehetken” viereisellä tiskillä. “Blackjack-turnaus, voittajalle haalarimerkki!” Kaikki huokaavat helpotuksesta — jotain tekemistä odotteluun.'),
(23,'Iso-Britannia','EGLL','Lontoon Heathrow’n kirjakaupassa päivän Wordle on kirjoitettu infonäytölle. “Ratkaise ennen boardingia ja saat haalarimerkin”, myyjä sanoo.'),
(24,'Luxemburg','ELLX','Luxemburgin lentoaseman kahvilan pöydällä on tabletti, jossa pyörii Hirsipuu. Jos arvaat oikean sanan ennen kuulutusta, saat haalarimerkin.'),
(25,'Espanja','LEMD','Madridin matkatavarakarusellin yläpuolella on numeroita. Jos onnistut arvaamaan minkä numeron kohdalla matkatavarasi pysähtyy, voitat haalarimerkin.'),
(26,'Valko-Venäjä','UMMS','Minskin porttialueella opiskelijajärjestö pitää kojua. Jos voitat kojun pitäjän kivi-sakset-paperi-pelissä, voitat haalarimerkin.'),
(27,'Venäjä','UUEE','Moskovan lentoaseman kahvilan tiskillä on kyltti: “Ratkaise matikkapulmat ja saat ilmaisen kahvin ja haalarimerkin.”'),
(28,'Kypros','LCLK','Nikosian lentokentän aurinkoiselle terassille on pystytetty Blackjack-pöytä. Voitosta jää muistoksi haalarimerkki.'),
(29,'Norja','ENGM','Oslon lentoaseman lahjapuodin myyjä ilmoittaa, että oikean sanan arvaaja saa ostokselleen alennuksen, sekä haalarimerkin.'),
(30,'Tšekki','LKPR','Prahan porttialueella matkustajat odottavat lentoaan pelaten Hirsipuuta digitaalisella taululla. Oikea sana paljastaa koodin, jolla voi lunastaa haalarimerkin infopisteeltä.'),
(31,'Ranska','LFPG','Pariisin Charles de Gaullen säilytystiskillä työntekijä järjestää pienen pelin: “Valitse lokero – yksi niistä kätkee pienen yllätyksen.” Valitse oikein ja saat haalarimerkin.'),
(32,'Montenegro','LYPG','Podgorican kentällä pubin tiskillä on kyltti: “Haasta baarimikko kivi–sakset–paperiin. Jos voitat, onnesi tuo haalarimerkin.”'),
(33,'Kosovo','BKPR','Prištinan terminaalin kahvila on täynnä opiskelijoita, jotka jakavat lentokortteja – mutta niissä on yhtälöitä. Ratkaise kaikki korttisi tehtävät oikein ja saat haalarimerkin palkinnoksi.'),
(34,'Islanti','BIKF','Reykjavikin lentoaseman loungessa väsyneet matkaajat ovat rakentaneet minikasinon. Jos voitat jakajan, saat haalarimerkin.'),
(35,'Latvia','EVRA','Riikan infonäytöllä pyörii sanapeli, johon matkustajat voivat osallistua puhelimillaan. Oikein arvanneet saavat haalarimerkin.'),
(36,'Italia','LIRF','Rooman lentokentän kahvilassa Hirsipuu pyörii pöytään upotetulla näytöllä. Arvaa sana niin saat kassalta haalarimerkin.'),
(37,'Bosnia ja Hertsegovina','LQSA','Sarajevon check-in -pisteellä virkailija vilkaisee näyttöä ja sanoo: “Jos arvaat, mikä numero toistuu lentosi varauskoodissa, annan sinulle haalarimerkin.”'),
(38,'Pohjois-Makedonia','LWSK','Kun annat passin tiskillä, virkailija kuiskaa: “Meillä on tänään peli. Jos voitat minut kivi–sakset–paperissa, saat haalarimerkin, jonka vain harvat saavat.”'),
(39,'Bulgaria','LBSF','Sofian lentoaseman kahviossa opiskelijaryhmä haastaa matkustajia “päässälaskumaratoniin”. Jos suoritat kierroksen ennen boardingia, he palkitsevat sinut haalarimerkillä. Mutta varo! Yksikin väärin ja et saa mitään.'),
(40,'Georgia','UGTB','Lentokentän pienellä pelialueella on automaatti, joka mainostaa: “Kokeile onneasi – voita jakaja ja saat haalarimerkin!” Automaatti piippaa, kortit vilahtavat ruudulla, ja jännitys kasvaa boarding-kuulutuksen yli.'),
(41,'Albania','LATI','Rahanvaihtotiskillä on kyltti: “Arvaa päivän sana, niin valuuttakurssien lisäksi haalarimerkkien määrä vaihtuu.”'),
(42,'Malta','LMML','Vallettan lentokentän rantateemaisessa kahvilassa pelataan Hirsipuuta. Kun arvaat sanan, tarjoilija antaa sinulle haalarimerkin.'),
(43,'Puola','EPWA','Portin työntekijä järjestää ajankuluksi pienen kilpailun: “Arvatkaa, mikä seuraavista porteista avautuu ensimmäisenä!” Voittajalle annetaan pieni muistaminen – haalarimerkki.'),
(44,'Liettua','EYVI','Vilnan odotusaulassa matkustajat kilpailevat kivi-sakset-paperilla viihteeksi ennen lentoa. Liityt mukaan, voitat kierroksen – ja saat haalarimerkin.'),
(45,'Itävalta','LOWW','Wienin lentoaseman kahvilassa tarjoilija testaa asiakkaiden laskupäätä ennen laskun maksua. Jos ratkaiset kaikki laskutoimituksen oikein, saat kaupan päälle haalarimerkin.'),
(46,'Kroatia','LDZA','Lentokentän yökahvilassa barista sekoittaa kortteja tylsistyneenä. “Tämä paikka nukkuu, mutta peli ei. Pelaatko kierroksen?” Hän napauttaa pöytää. “Blackjack – ja jos voitat, ansaitset haalarimerkin.”');
