import mysql.connector


yhteys = mysql.connector.connect(
    host="localhost",
    user="JonatanGM",
    password = "123",
    autocommit = True,
    db = "lk_approt",
    port = 3306
)

cursor = yhteys.cursor()

cursor.execute("USE flight_game")

cursor.execute("DROP TABLE IF EXISTS hirsipuu")

cursor.execute("CREATE TABLE IF NOT EXISTS hirsipuu ("
               "id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,"
               "sana_hard VARCHAR(40),"
               "sana_easy VARCHAR(40))")

sanat_hirsipuu_hard = """ABSTRAKTI ANOMALINEN KROMATIINI HYPOTEESI KVAASARI SYMMETRIA PANOROIDA ENTROPIA FRAKTAALI HELIOSENTRINEN KYTKEYTYÄ BIOMETRIA QUASAR POLYKROMINEN ZYKLONI LABYRINTTI MNEMONINEN PSYKOLOGINEN TOPOGRAFIA KRYPTINEN VALENSSI BIOLUMINESCENSSI RAHKASAMMAL ONTOGENEESI HIERARKIA PARADIGMA XENOFOBIA REGRESSIO YHDENTYMINEN SYKLINEN FUNKTIO GRAFEEMI AMBIGUOUS LOGARITMI STRUKTUURI FOTOSYNTEESI NOSTALGIA INTEGRAALI KOORDINAATTI POLYMORFIA KALIBROINTI GENOMI ANEMIA KATALYYTTI HEMISFÄÄRI OKSYMORON RAKENTUA MUTAATIO IDENTITEETTI DEGENERAATIO SUPRANOVA GALAKSI METRIKKA SURREALISMI TOPOLOGIA EPISTEMOLOGIA DIAGONAALI MONADI FORMULAATIO RESURSSI RADIKAALI ALGORITMI SATUROITUVA REFLEKTIO QUOTIENT SPEKTRI LASKUTOIMITUS HOLOGRAMMI JÄRJESTELMÄ PRAGMAATTINEN TEKSTUURI SATELLIITTI KOMPLEKSI RELATIIVINEN DILEMMA AKSIOOMA SYMBOLI SEMIOOTTINEN KUMULOITUVA EVOLUUTIO ORNAMENTTI VALENSSI HERMENEUTIIKKA PARADIGMAATTINEN DYNAMIIKKA YHDISTELMÄ METAFORA ERIYTYMINEN KRONOLOGIA HYPERBOLA PLASMA NEUROVERKKO STOKASTINEN PIILOSANA FILOSOFIA RADIAANI HOMOGEENINEN DIFFERENTIAALI FRAASIVERBI SÄTEILY KONTEKSTI MORFOLOGIA ZETTA JOUSTAVUUS ISOTROPIA PROJEKTIIVINEN ULTRAÄÄNI DETERMINANTTI KOMPROMISSI SPEKULAATIO
"""
sanat_hirsipuu_easy = """AIHEUTUA ALOITE ANNOSTELLA AURINKO BIISI DOKUMENTTI ETENEMINEN FIKTIO GALAXIJA HARRASTUS IDEOLOGIA JUONI KAMPAUS KARTTA KIRJALLISUUS KOMENTO KUVAUS LAITE LAASTARI LUKU MATERIAALI MAHDOLLISUUS MUOTO MUSIIKKI NÄKYMÄ OPPIMINEN PELI PERSOONA PROSESSI PUITTEET RAKENNUS RATKAISU SÄHKÖ SUUNNITELMA TEHTÄVÄ TOIMINTA TAPAHTUMA TYÖKALU TAPA TAVOITE TIETO TUTKIMUS ULOTTUVUUS VALINTA VAIKUTUS VAIKUTTAA VÄLINE YHTEYS YMMÄRRETTÄVÄ YLEISÖ YKSILÖ ÄLYKÄS ÄÄNESTYS PÖYTÄ TUOLI KIRJA LAMPPU IKKUNA OVI KYNÄ KUMI REPPU PUSSI KELLO SÄHKÖ JOUSI PELI PUHELIN HIIRI NÄPPÄINEN LAATIKKO KENGÄT TAKKI HAME HATTU LIPPU AVAIN TALO AUTOSSA POLKU SILTA PUU KUKKA VESI JÄRVI MERI SAARI PILVI SÄDE TUULI LAMMAS LEIPÄ KALA OMENA APINA LAMPPU PÖLY HARJA HAMPAA TALO LAPSI KOIRA KISSA
"""
hirsipuu_easy_list = []
hirsipuu_hard_list = []

for sana in sanat_hirsipuu_easy.split():
    hirsipuu_easy_list.append(sana)
for sana in sanat_hirsipuu_hard.split():
    hirsipuu_hard_list.append(sana)


for sana in range(len(hirsipuu_easy_list)):
    cursor.execute("INSERT INTO hirsipuu (sana_easy, sana_hard) VALUES (%s, %s)",
                   (hirsipuu_easy_list[sana], hirsipuu_hard_list[sana]))

